import os

# Logging level
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_LEVEL_ZOLA = "WARNING"
DEFAULT_LOG_LEVEL_LIBRARIES = "ERROR"
ENV_LOG_LEVEL = "LOG_LEVEL"
ENV_LOG_LEVEL_LIBRARIES = "LOG_LEVEL_LIBRARIES"

# ENCODING
DEFAULT_ENCODING = "utf-8"

#Yaml version
YAML_PARSER_VERSION = "1.2"
